version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/my-inventory
      - JWT_SECRET=supersecretkey123!@#sureshaddinv
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
